# Generated by Django 4.1.3 on 2022-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now=True, null=True)),
                ('region', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('units', models.IntegerField(default=1)),
                ('unitPrice', models.FloatField()),
                ('saleAmount', models.FloatField()),
            ],
        ),
    ]
